permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "DevSkills"
email: "jkson21@naver.com"
description: "andrewthecoder"
github_username:  "andrewsohn"
swiftype_searchId: "tzCuXdbWqAVdUv-77RbH"
disqus_shortname: "andrewsohn"



url: "http://andrewsohn.github.io"
imgrepo: "http://andrewsohn.github.io/static/img"


# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"
gems: [jekyll-paginate]

